coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        base: auto
        informational: false
        if_not_found: failure
    patch:
      default:
        target: 90%
        threshold: 0%
        base: auto
        informational: false
        if_not_found: failure

ignore:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/test/**'
  - '**/tests/**'
  - '**/e2e/**'

comment:
  layout: 'reach,diff,flags,files'
  behavior: default
  require_changes: false

flags:
  web:
    paths:
      - apps/vela/
  api:
    paths:
      - apps/vela-api/
  ext:
    paths:
      - apps/vela-ext/
