name = "vela-app"
compatibility_date = "2025-08-01"
main = "./worker/index.ts"

[assets]
# Serve the Quasar SPA; unmatched navigations fall back to index.html
not_found_handling = "single-page-application"
# Ensure API routes hit the Worker first (even for navigations)
run_worker_first = ["/api/*"]

[vars]
APP_NAME = "Vela Japanese Learning App"
# Secrets to set via `wrangler secret put`:
# - GEMINI_API_KEY
# - OPENROUTER_API_KEY
# - (optional) GOOGLE_AI_API_KEY
