[test]
coverage = true
coverageSkipTestFiles = true
coverageThreshold = 0
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = [
  "**/*.test.ts",
  "**/*.spec.ts",
  "src/types.ts",
  "src/tts/types.ts",
]
