import type { MysteryChapter } from './model';

export const MESSAGE_THAT_ARRIVED_TOMORROW_CHAPTER = {
  id: 'mystery-message-tomorrow-v1',
  version: 2,
  title: '明日からのメッセージ',
  startSceneId: 'scene-01',
  targetPhrases: [
    {
      id: 'tomorrow-seven',
      text: 'あしたの朝7時',
      reading: 'あしたのあさしちじ',
      meaning: 'tomorrow at 7 a.m.',
    },
    {
      id: 'mina-possession',
      text: 'ミナさんのです',
      reading: 'ミナさんのです',
      meaning: "it is Mina's",
    },
    {
      id: 'train-station-plan',
      text: '7時に電車でさくら駅に行きます',
      reading: 'しちじにでんしゃでさくらえきにいきます',
      meaning: 'I will go to Sakura Station by train at 7',
    },
    {
      id: 'wrote-yesterday',
      text: 'きのう書きました',
      reading: 'きのうかきました',
      meaning: 'wrote it yesterday',
    },
    {
      id: 'when-is-tomorrow',
      text: '「あした」はいつですか？',
      reading: 'あしたはいつですか',
      meaning: 'When is “tomorrow”?',
    },
    {
      id: 'say-again',
      text: 'もう一度言ってください',
      reading: 'もういちどいってください',
      meaning: 'Please say it again',
    },
  ],
  scenes: [
    {
      kind: 'message',
      id: 'scene-01',
      speaker: 'mina',
      text: 'こんにちは。これは「あした」からのメッセージです。',
      ttsId: 'mystery-message-tomorrow-v2-scene-01',
      nextSceneId: 'scene-02',
    },
    {
      kind: 'message',
      id: 'scene-02',
      speaker: 'mina',
      text: 'あしたの朝7時、電車でさくら駅に来てください。青いノートを持ってきてください。',
      ttsId: 'mystery-message-tomorrow-v2-scene-02',
      nextSceneId: 'scene-03',
    },
    {
      kind: 'choice',
      id: 'scene-03',
      speaker: 'mina',
      prompt: 'ミナさんは、いつ駅に来てほしいですか？',
      audioPrompt: {
        ttsId: 'mystery-message-tomorrow-v2-scene-03-prompt',
        text: 'ミナさんは、いつ駅に来てほしいですか？',
      },
      options: [
        {
          id: 'tomorrow-morning',
          label: 'あしたの朝7時',
          result: 'correct',
          feedback: '「あしたの朝7時」と答えました。',
          nextSceneId: 'scene-04',
        },
        {
          id: 'today-morning',
          label: 'きょうの朝7時',
          result: 'incorrect',
          feedback: '「きょうの朝7時」と答えました。',
          nextSceneId: 'scene-04',
        },
      ],
      hint: '「あした」は、今日の次の日です。',
      explanation: '「あしたの朝7時」は、今日の次の日の朝7時です。',
      targetPhraseIds: ['tomorrow-seven'],
    },
    {
      kind: 'message',
      id: 'scene-04',
      speaker: 'haru',
      text: 'さくら駅で青いノートを見つけました。ノートに「きのう、ここに置きました」と書いてあります。',
      ttsId: 'mystery-message-tomorrow-v2-scene-04',
      nextSceneId: 'scene-05',
    },
    {
      kind: 'choice',
      id: 'scene-05',
      speaker: 'haru',
      prompt: '音声を聞いて、青いノートはだれのものか選んでください。',
      audioPrompt: {
        ttsId: 'mystery-message-tomorrow-v2-scene-05-audio',
        text: '青いノートはミナさんのです。きのう、駅に忘れました。',
      },
      options: [
        {
          id: 'minas-notebook',
          label: 'ミナさんのノートです',
          result: 'correct',
          feedback: '「ミナさんのノートです」と答えました。',
          nextSceneId: 'scene-06',
        },
        {
          id: 'harus-notebook',
          label: 'ハルさんのノートです',
          result: 'incorrect',
          feedback: '「ハルさんのノートです」と答えました。',
          nextSceneId: 'scene-06',
        },
      ],
      hint: '「ミナさんのです」の「の」に注目してください。',
      explanation: '「ミナさんのです」は「ミナさんのものです」という意味です。',
      targetPhraseIds: ['mina-possession'],
    },
    {
      kind: 'message',
      id: 'scene-06',
      speaker: 'mina',
      text: 'そうです。きのう、駅に忘れました。でも、このメッセージもきのう書きました。',
      ttsId: 'mystery-message-tomorrow-v2-scene-06',
      nextSceneId: 'scene-07',
    },
    {
      kind: 'response-build',
      id: 'scene-07',
      prompt: 'ミナさんに、あしたの予定を伝えてください。',
      tokens: [
        { id: 'station', text: 'さくら駅' },
        { id: 'ni-time', text: 'に' },
        { id: 'period', text: '。' },
        { id: 'train', text: '電車' },
        { id: 'go', text: '行きます' },
        { id: 'time', text: '7時' },
        { id: 'de', text: 'で' },
        { id: 'ni-place', text: 'に' },
      ],
      correctTokenIds: ['time', 'ni-time', 'train', 'de', 'station', 'ni-place', 'go', 'period'],
      alternateAnswerTokenIds: [
        ['train', 'de', 'time', 'ni-time', 'station', 'ni-place', 'go', 'period'],
        ['time', 'ni-time', 'station', 'ni-place', 'train', 'de', 'go', 'period'],
      ],
      feedback: {
        correct: '予定をはっきり伝えられました。',
        incorrect: '返事を送りました。自然な語順の例も確認しておきましょう。',
      },
      hint: '時間の「に」を先に、行き先の「に」をあとに置きます。',
      explanation: '「7時に」で時間、「さくら駅に」で行き先を表します。',
      targetPhraseIds: ['train-station-plan'],
      nextSceneId: 'scene-08',
    },
    {
      kind: 'message',
      id: 'scene-08',
      speaker: 'haru',
      text: 'ちょっと待ってください。メッセージは今日届きました。でも、ミナさんは「きのう書きました」と言いました。',
      ttsId: 'mystery-message-tomorrow-v2-scene-08',
      nextSceneId: 'scene-09',
    },
    {
      kind: 'choice',
      id: 'scene-09',
      speaker: 'haru',
      prompt: '今、何を確認するのが一番いいですか？',
      audioPrompt: {
        ttsId: 'mystery-message-tomorrow-v2-scene-09-prompt',
        text: '今、何を確認するのが一番いいですか？',
      },
      options: [
        {
          id: 'ask-when-tomorrow',
          label: '「あした」はいつですか？',
          result: 'correct',
          feedback: '「『あした』はいつですか？」と聞きました。',
          nextSceneId: 'scene-10',
        },
        {
          id: 'ask-notebook-color',
          label: 'ノートは何色ですか？',
          result: 'incorrect',
          feedback: '「ノートは何色ですか？」と聞きました。',
          nextSceneId: 'scene-10',
        },
      ],
      hint: '今の謎は、日にちのことです。',
      explanation: '「いつですか？」は、時間や日にちを確認するときに使います。',
      targetPhraseIds: ['wrote-yesterday', 'when-is-tomorrow'],
    },
    {
      kind: 'message',
      id: 'scene-10',
      speaker: 'mina',
      text: 'メッセージを書いたのはきのうです。きのうの「あした」は、今日です。',
      ttsId: 'mystery-message-tomorrow-v2-scene-10',
      nextSceneId: 'scene-11',
    },
    {
      kind: 'response-build',
      id: 'scene-11',
      prompt: '説明をもう一度聞きたいと伝えてください。',
      tokens: [
        { id: 'please', text: 'ください' },
        { id: 'period', text: '。' },
        { id: 'again', text: 'もう一度' },
        { id: 'say', text: '言って' },
      ],
      correctTokenIds: ['again', 'say', 'please', 'period'],
      feedback: {
        correct: '丁寧に聞き返せました。',
        incorrect: '返事を送りました。自然な言い方の例も確認しましょう。',
      },
      hint: '「もう一度」は “one more time” です。',
      explanation: '「もう一度言ってください」は、同じことをもう一回聞きたいときに使います。',
      targetPhraseIds: ['say-again'],
      nextSceneId: 'scene-12',
    },
    {
      kind: 'message',
      id: 'scene-12',
      speaker: 'mina',
      text: 'きのうの夜、このメッセージを書きました。でも、送ったのは今日の朝です。だから、きのうの「あした」が今日になりました。',
      ttsId: 'mystery-message-tomorrow-v2-scene-12',
      nextSceneId: 'scene-13',
    },
    {
      kind: 'ending',
      id: 'scene-13',
      title: '「あした」の正体',
      text: '未来からのメッセージではありませんでした。きのう書いた「あした」のメッセージが、今日届いただけでした。青いノートもミナさんのものだと分かり、謎は解けました。',
      ttsId: 'mystery-message-tomorrow-v2-scene-13',
    },
  ],
} satisfies MysteryChapter;
